resources:
- repo: self

pool:
  vmImage: Hosted VS2017
steps:
- task: ottostreifel.spellcheck-task.spellcheck.spellcheck@2
  displayName: 'Spellcheck **/*.md'
  inputs:
    files: '**/*.md'
    whitelistedWords: 'whitelist_spellchecker.txt'

